// src/components/ui/AsciiArtPortrait.jsx
import React from 'react';
import "./ascii-art_portrait.css"; 

const AsciiArtPortrait = () => {
  return (
    <section className="ascii-portrait" aria-label="Portrait von Roman Messmer">
      <div className="ascii-portrait__container">
        <pre className="ascii-portrait__pre deselect">
{`                                                                                                                                                                                                                               ,:.                                 . .  .. .........,,,.,,,,,,,,,,::;;;;;;;;
                                                                                                                                                                                                                               ,:            ...                     .  .............,,,.....,,,,..,,:;;;;;;
                                                                                                                                                                                                                               ,:                                      .....................,,,,,,.,,::;;;;;
                                                                                                                                                                                                                               ,:                                        ....  .........,,,,,,,.,,,,,,,;;;;;
                                                                                                                                             ,;+IYVXRRRRXXXYYi,.                                                               ,:          .                 .           ...............,.....,,,.,,,..;;:;;
                                                                                                                                     .;IXRMW#WWWMMBBBBBBBBBBM#W##MRXI=                                                         ,,                                     ................. .,....,.,.,,,,,,:;;;
                                                                                                                                ;IB####MBRXVIttttiiiiiittiiitiitIIYXBW#WBI+.                                                   ,,                                      ...... ..   ...........,,,,..,,,.,:;;
                                                                                                                           :YB###MXYYIt+++iiiii+iiiiii+++iiii+iii++iittYXRBBRVi                                                ,,          ...                         ....   ... ....,.......,,,,,.,,,.,,:;
                                                                                                                      .=IB##WRYIti+=+++++++itti+==+++++++iiti+++++ii+++++itIVBWBV+,                                            ,,                                       ...  .............,,,,,,.,,,,,,...,:
                                                                                                                   iB###BVi=;;==;;;;;;====;;==+i+===++++iitti++===++iitti+++iitIVXRXt.                                        .,:                                             .    .... .......,,......,...,
                                                                                                               ;IM##BIti+=;;===;;;;;;==;;;;:;;;==;;;====++i+++++====++iiiiiiiiiiittIYXY=                                      .:,                                         .    .    ... ......,........,,,,,
                                                                                                            :YM##RVti=========;;;;::::;;;=====;:;;;;;;;=======+++==;===+++i++ii++iiiitYVI=                                    .,,                                   .   ...  ......   ...............,.,,,..
                                                                                                         .Y##MXI+++=;:;;;;;:,,,,:,,,::;:::,,,,,,:;;;::;;;;;;;========;;;====++++++++++==itI+.                                 .:,                                         ...   ...  .. ...............,,...
                                                                                                       ;X#WRYti====;:;:;::::::,,,,,,::;:::,,,::;;;;;;;;;;;;;=========;;;====;=+==+++iii+=+tti:                                .,,                                                  .... ....................
                                                                                                     I##MYtt;;;;;::::::,,,,,,,:::::::,,,:::;;;::::;;;;;;;;;================;;==;;==++=;;;+==iII;                              .,,                                 ....  .           ... ...........,,,,,,,.,
                                                                                                   +BWRYIi=;;=;;;::::,:,::::,,,,::::,:::::::;;;;:,,:;;::;;;:::;;===================+++==+=;;;=++;.                            .,.            .                                            ...,,,,,,,,,,.....
                                                                                                 +##MVIt+;;+=;;;;:::::,::,::,,,,,,,::,,:::::::;=;::::;;;;;;::,:::::::::;;;;;===;;;;;==+i+;:,,:;;++;                           .,.                                       .:=itIYYYIIIt+;:,..                 
                                                                                               ;XBRIi++=;:::::::,,,,,,,,,,,:::::::::::::::::,,:::::::::::::;;;::::::::::::::;;=;;:::::::::::::;:,:;:.                         .:.                            .  ....,;tttti++==;:.                          
                                                                                              iW#XYi+=;::;::,,,,,,:::::,,,::::::::::::::::::::::::::,,:::::;;;:::::::::::::::::;;;;:::::,::::,::::;=;,                        .:.                         .,,,,,... .,                                      
                                                                                            +RMXIiii++;:::,;:::,,,::::::::::,,,,::::::::::::::::::::,,,,,,,,:::::,,,,,,::::,,,,:::::,,:;:::::::;;:::;;,                       ,:.                                                                           
                                                                                           VMBVI++;:::,,,,,,,,,,:,,,,::::::::::::::::,,,,:::::::,,,,:::,,,,,,,,,,,,,,,,,::,,::::,,,:::::::::::::::::;;=;                      ,:                                                               ..,,::;;;====
                                                                                         tMMXIti=t=;;:::::,,:::::::::,,::,,,,:,,:::::::,,,,,,::::::::,,,,,,,,,,,,,::::::,,,,,,,:::::::::,::::::::::::::;,                     ,:                                                ..,::;;==+++++iiiiiiii+++++=
                                                                                       .IWBYiiti=+,,::,:,:::::::::::::,,,,::::,,,,,,:,::::,,,,,,::,:,,,,,,:,,,::,,,,,,,,,,,,,,,,,:::,,:::::::::;:::::::;=;.                   ,,                             .,,,:::;;;===++++++++++++===========;;;===;====
                                                                                      i##Vttiii++=;::,,,,:::::,,,,::::::::::::::::::,,,:::,,,:::,,,,,,,,,,:,,,,,,,,,,,,.,,,,,,::,,,,:::,::::::::::::::::;=;.                 .,,          ,...,,,,::;;;==========+=======++===========+=====================
                                                                                    ,YBXiIIIIti+++;:::::::::::,,::::,,,:::::,:::::,,,,,,,,,,,,::,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:::,,,::,,,::::::::::::;:::=;,                .,,         ,+IIIIIttti+++++============+=;========================+===++======
                                                                                   iBBVttiIiii+=+=:,:::::::::::::::::,,,:::::,,,,,,,,,,,:::,,,,:,,,,,,,,,,,,,,,...  ...,..,...,,,,,:,,,,:,:,,:::::::::::::;=;,               .:,           =++++++=++++++++++++================+==+=============+=========+=
                                                                                  +RVtittitii+==++;::::::::::::::::::,,::::::::::::::::::::,,,,,,,,,::,,,.   ................   ..,,,,,::,,,:::::::::::::::;=:.              .:,           .;+=;=======+++++++++++++++++++++++=++====+==++======++==========
                                                                                 VRVi+ititiiii++++;:::,,::::::::::::::,,,,,:,:,,::::,:::::,,,,,,,,,,,..  ..................,,...,,,,,,,,,,::::::::::::::::::;=;:             .,,            .;=;;;==;;=========++++++i++iiiiii++++++++++++++++++++++++++++++
                                                                                IMIitIItittii++==++::::::::,::::,:,,,::,,,,:,,,,,,,,,,,,,,,,::,,....   ..,,..           ..,,..,,,,..,,,,,,:::::::::,,:::::::;;;;.            .,.            .:;;===;========+=======++==+++++++iiii+iiii++++++++++++++++++++
                                                                              .iRiitIIttti++tti+===;:::::::::::::::,,:::::,,:::::::::,,,,:,,,,........                     .........,,,,,,,,,,,:::,,:::::::::::;:            ,,.              .:==;;=;;;;====+=====+++++++++===+++++++++++++++++++++++++++++
                                                                              tXIittiitIi==ittt+==;:;::::::;::::::::::::;:::::::,,,::,,,,,,,,,,,,,..                         .,,.....,,,,,,,,,,:::,,:::::::::;;;;,           ,:.               :;;:=;;;;=;==;=====+++=i+++++i++++++++++++++++++++iii++++++ii
                                                                            .tRttttiiiiti+itti+=;=++=;::::,,,:,,,::::::,,,,,::,:,:,,,:::,,.,,,,,,..                           ......,,,,::::,,,,,::,,::,:::::;;;;+:          ,:.                ,;;:;;;;;;==;=======+=+++++++++++++++++i+++++++++++++i++iiii
                                                                            ,tt+tittti+++=ii+++++==+=;::::,,,,::::::::::,:,,,:::,,,::::::::,,,,,......                      .......,,:,,::::::::,:::::;:::::::::;=;          ,:.                .,;=;;;;;;==;=======+=+++++++++++++++++++++++++++++++++++iii
                                                                           :YYit+iiiiiiiiii++=++++==;:::;;::,,:::::::::::::,,:,,,,,,:,,,,,,,.....,,,,.               ..... ..,,...,,,,,.,,:,,,,,,,,,::::::::;:::;=+:         ,,.                  ,=;;;;;;==;======+=+++++++++++++++i+++++++++++++++++++++++
                                                                           tVIiIitii+iiiii+iii++====;;;;;;::::::,,,:,:::::::::,,,,,,,,,,,,,,,,,,,,,.     ..                  ...........,::::,:,,:::::::::::;;;;;;+;.        ,,.                  ,:;;;;;===;=========++++++++++++++++++++++++++++++++++++++
.                                                                         =YIiiiIttiii+=+ii++++=+=;=====;;;;;::::::::::,,:::,,,,,,,,,,,,,,.,,,,,,.........                   .....,......,,::::,,,,,,:::::::::::::;=;.       ,,.           .        ::;;;;;;=;;;======+++++==+++++++++++++++++++++++++++++ii
YXXRRRRRRXXXXXRXXXXXXXXVVYYItti+=;;:...                                   +Ytii;ttttii++iti+===+++======;;::;;::::::::::,,::::::,,,,,,,,,,,,,,,,,,,..                          ...........,,,,:,,,,,,::,,:::::;;:;:;=:       ,,            .        .:;;;:;;;=======+=++++++++++++=++++=++++++++++++++++++++
YYYYYYYYYYYYYYYYYYYYYYYYYYYYVVVXXXXXRRRXXXXRRXXXRRRXXXXYIYVVYIYtttii++==;+VVIttiYti+++++=+ii++++======;;;;;::::::::,,,:,:,:::::,,,,,,,,::,,,,...,....                            .    ....,::,::,:,,::::::::::::::::;:.      ,,                      .:;;;;;;===;=====++++++++++++++++++++++++++++++++++++++
VVVVVVYVVVVVVVYVVVYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYVVVVVVVVYYYYVYYYVVVVVVXVXYIti+ii+==+i++++i+iii++====;;;;;;;:::::::,,,,::::,,:,,,,,,,,,,,,,,,..,,,,.,..                    ..  ..,,.......,,,,,,,,,,::::::;::::::;;;==,      ,,                    .  .:;;;::;;======+++++++=++++++++++++++++++++++++++++=++
VVVVXVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVYVVYYYYYYYYIYYYVVVVVVVYYYYYYYYYYYYYYIYIItiittiiiii+==+=++++++++==;;;;;::;::::;;:,::,,,,,::,,,,,,:,,,,,,,,,,,,,.....                        .   .   ...,,,,.,,,,,,,,,,::::::::;;;==:      ,,                        ,:=;;;;;;=====+=+++++=+++++++++++++++++++++++++++++++
XXXXXXXXVVVVVVVVVVVVVVVVVVVVVVVVVVVVYVVVVVVVVVVVYYYYYYYYYYYYVVVYYYYYYVVVXVItttttI++ii++=+i++++===+====;;;;;:;;:::;;::::,,,,::,:,,::::,,,,,,,,,,,.,..                                . .........,,,,,,,::::::::::,::::;:.     ,,                     .  .,:;=;;;;;=====+==+++==+=+++++++++++++++++++++++++i++
XXXXXVVVXXXVVVXXVXXVVVVVVVVXXXXXXVVVVVVVVVVVVVVXVVVVXXVVVXXXVVVVVVVVVVVVIIIYItiittiii++iiii++===+++=;;;=;;;;;:::::::::::,::::,,::::::,,:,,,,,,,,,::,,....   .                         .. ......,,:,,,,:,,::::::;;;;;;;;,     ,,                     .   .,;;=;;;;====;++===+++==+++++=++++++++++++++++++ii++
XXXXVVXXVVVVVVVXXXVVVVXXXVVXXXXVVVVVVVXVVVVXXVXVXXXXVVXVVVVVVXXVXVVVVVVVIYIIIttiII++++++i+++++++++=;;;;;=;;:;;;:::;:,,,,,,,,,:,,,,,,,,,,,,,,,,,,,:,,,,.              .   ..........    .......,...,,,:,,,:::::::;::::;;:    .,.            .             ..:;;;;;;;===++======++++++++++++++++++=+++++++++++
XXXVVVVVXXVVXXXXXXXXVVXXXXVVVVXXXXXXXXXXVVXXXXXXXXXXXXXVXXXXXXXXXXXXXXXXVVYIIIttYIiiiiiii+ii+=;;==+==;;=;;;:;;;;;;;::,,,,,,:::::,,,,,,,,,,,,,,,....,.......              .....,.....        ......,,,::::::::::::::::;;:.   .,.            ,.         .   .,;;;;;;;=+=++====+===++++++++++++++=+++++++++++++
XXXXVVVXXXXXXXXXXXXXXXXXXXXVXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXRYYIIIIIIIiitIt++iii++=;;;=+++=;;;;;;;;;;::::,,,,,,,,::,,:::::::,,,,,,,,......... ...                 ... .. .,...   .  ..,,,,,,::::::::::;:;;;==:   .:.                       ..   ..;;;;;;=========++=+++++++++==+++==+++++++++++++
VVVVVXVXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXVXXXXXXXRIYYYYYYIItiiiiii+=++======+======;;::;;;::::,::,,,,,::::,,,,,,,,,,,,,,,,,,,,,..   ..              ...,,....  ..      .....,,,::,,,::::::::::::;=:   ,:.                       ....   ::;=;;;============++++++==++==++=+++++++++++++
VVVVVVXXXXXVXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXRXXXXXXXXRRXXXXXXRXXXXXXXXRVYYIItIIIYttttiiii++++++++====;====;;;;:::;;:;:::,,.,:::,..,,,,,,,,,,,,.,....,,,,,..                . ..,....      .......,,,,:,,:::::::::,:::;==   ,:.             ..          .... .,;================+=+++++=++++++++++++++++++++
VVVXXXXXXXXVXXXXXXRXXXXXXXXXXXXXXXRXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXRRRBVYIIIttIYtitti++ii+==+++==+==;;;;=;;;;;:::;;:;::,,,,,,,,,,,,,,,,,,,,,,,..........,,...,..           . ..................,,,,,::,:,:::,:::::::::;;   ::.                        ...  . .:;;=======++==+++++++===+++===+++++++++++++++
XVVVXXXXXXXXXXXRXXXXRXXXXXRXXXXXXXXXXXXXXXXXXXXXXXXXXXRRRRRRRRRXXXXRRRRBItIYYIIIYYIIIi++ii++++++======;;;;;:;;;;:::;;::::::,,.,,,,,,.,,,.,,,,,,.,,,,,,,.......,,,...    .  ...,....,,..,,,..,...,,,,,:::::,:::::,::::::;=:                                 ..  .:;=;;=============++===+===+++++=+++++++++++
XXXXXXXXXVVVXXXXXXXXRRXXXRRXXXXXXXXXXXXXXXXXXXXXRXXRRRXXXXXXXXXRRRRRRRRBXVYYYItttIiii+++ii+i++==++=;========;;;::::;;;;::,,,,,,,,,,,,,,,..,,,,,..,,,,,,,,,,,,...........,.....,,,,,,,,,,,,,,,,,,,,,,,::,,:::::::::::::::;iII+,           ..              ..... .,;=================++===+=+++++==+++++++++++
XXVVVXXXVVVVVXXXXXXXXXXRRXXXXXXXXXXXXXXXXXXXXXXXXRRRRRXRXRXXXXXRRRRRRRRBVYYYYYIIIt++i++iii+++===============::;;::::,:;::,,,,,,,,,,,.,,,....,......,,..,,..,,,,.,,,,,,,,.,,,..,.,.,,,,,,,,,,.,,,,::::::,:::::::,::;;;::::.IBWMY:          .              ........,:=+=======+=+=======+=++++===+++++=+++++++
XXVVVXXXXXXXXXXXXXXXXXXXXXXXXXRRXXXXXXXXXXXXXXXRRRRRRRRRRRRRRRRXXRRRRRRBXYYYYYIItIttttiitii+==========;;;;;::;;;::::,:::::::,.,,,,,..,,,,.,,,,,.,,,,,...,..,,,,,,,,,,,,,,,,,,,,...,,,,,,,,,,,,,,,::::::,,,,,,...,,.,,,,,:,:tVXBWMI                          . ....,;=;===========++===+=+======+++=+++++++++
VXVVVXXXXXXXXXXXXXXXXXXVXXXXXRRRRXXXXXXXXRRRXXXRRRRRRRXRRRRRRRRRXXXRRRRMRVYIIIIIItttttttttti==++==+;;:::::::;;;;:::::::,,,,,,,,,,,,,,,,,,,,,,,,,,,,,::,:,,,:::::,,,,,,,::,,,,,,,,,,,,,,,,,,:::::::::;;===++iitttii+======:,+VRRXXM#V:                      ... .....:==========;=++++++=====++++++++++++++++
tIIYVXXVVXXXXXXXXXRXXXXXXXXXXXRRRXXXXXXXXXRXXXXRRRRRRXXRRRRXRRRRXRRXRBBMXVYYYYIIItttiii++it+++i+=;;;;;;;;::::;;;;:;::::,,,::,,,,,,,,,,,........,,,,,,,,,,,,,,,,,,,,,,,:::,,,,,,,,:::,,,:,,::::::::,:;=iiiIYYVVVVVYYIttIIIi=+IXRXVVXR#X:                    .........,;========;=========+++===+++++++=+++i++
VXXXVVVVVVVXXXXXXXXXXXXXRRXXXXXXXXXRXXXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRBMXVYYYYItiiiiii++++tti+=;;;:;::;;;;:;:;;:::;;:::,,,,,,,,,,,,,,,,,,,.,,,,,..,,,.....,,,,,:,::::::::::::::,,::::,,,::::;:::;==+ttIIIYVVVVVVVVYYIIYVXXVYYYVXXXVXXBBI.                  . ,.......,=====================+++++=++=++++++++
RRXXVVVVVVVVXXXXXXXXXXXXXXXXXXXXXXRXXXXXXRRRXRRRRRRRRXRRRRRRRRRRXRRRRRBMXXYIIIIttttttttttiiii=;:;;;;:::;;;:;;;;:,::;::::,,,,,,,:,,,.,::,....,,,. ...,,,,,,::;=====;;;;;;;;;:,,,,,,:,,:,::::;;;;;=++itIIIIYVVVVVVXRRRXXXXXVYYIYVXXXXVXYRWR.        .          .........;;===================++++=====+++++=++
XXXXXVYYYVVVXXXXXXXXXXXXXXXXXXXXXXRXXRRXXRRRXRRRRRRRRRRRRRRRRRRBXRRRRBBMXVIIIIItiIIttiii++i++=;;;==;;;;==;==;;;:::::::,,,:::::,,,:,,,,,,:,,:::;;=++++iIYVXXRRRXVVYItti+=;;;::::::::::,:::::::;=;=+itIIIYYVVXXRRRBBBXVt+=+iitIYXXXXXRVXXRMM=                  ......,,..,;=====;=============++====++++++++++
XXXXVYYYVVVVXXXXXXXXXXXXXXXXXXXXXXXXRRXXXXRXXRRRRRRRRRRRRRRRRRRBXRRRRBBBRVItIIItittiiitti+tti+==;;;::;;;;;;=;;;;:::::::::::,.....,,:;;=+++++==iitIIYYVVXXXXXXRXVVVVVYIIi+=;;:::::,,,,,::::::;==;=+itttttttIYVVYYIYti+=;;==;=iIVXXXXXVXXVXBWt        ..     ........,,. ,;========;;;=====+====++==++++++++++
XXXXYIIYVVVVXXXXXXXXVVXXXXXXXXXXXXRRXXRRXXXXXXXRXRRRRRRRRRRRRRRRRRRRBBBBRXYYIItItttIIti+iiIi+++=;:=;;;;;::;;;;;;;;;::::::,..,:;===;;=iiii+++iIYYYIIYVXXXXXXXXVYIItIttiiii==;::::,,,,::::::::;==+itttttttIiii+=::,,. .... ,,:;tVRBBMBMBBRRXBWMI               .....,,,,,,,:==;=====++============++++++++++++
RXVItIYVVVVXXVVVVVXVVVXXXXXRXRRXXXXXRRRRRRRRRXRRXRRRRRRRRRRRRRRRRRRRRBBBBRYYYYIIIIIItiiiitii+++===;+====;;;;;;;;;:::,:::;;;:;+iiiiiittIttIYYYIIIYVXRRRXXXVYItti++ii++++======;:::,.. ..,,,,:::;=tIIYIi++=:,.     ,:;;=itttIIIIItti=tVVXBMBBXRWMI.  .       . ......,,,,.,,:;======================++++=+++++
XVIIIYYYYVVXVVYVVVXVVVXXXXXXXXXXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRBBBBBVYYYIIItttttiittiii++==;;;;;::;;;;;;;;;::::;;;==;;+tttttIYVYYYYYItitIYVVVXXVYIIttttttiiiiiiiii+===::,::,,.   .,,:,::;+Ittti+=;;==+itYVXXVVVYIti====+itIt:      ;XRXXBWR;           ........,,,..,:==;========++====+++==++++=+++++
XYIIIYYYYVVVVVVVXXXXVXXXXXXXXXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXRRRRRBRBVIIIIttittttttiiIi+++=;;+;;;::;;;;;;;;;;;;=;=iiiittti+++ii+=;::::;;;;;;:::,,,,.,::;:;;;;;;;;;;:..    .,:,.    ,,,::::+ti++itIYVVYItti=;:::::;=++=;=iIVVVX=,:;==;;IIItVBY           ........,,,,..,;=;==============+++===+++=+++++
VIIYYIIYYYYYYVVVVVVVVVVXXXXXXXXXXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRBBBBMXYYYItiittttttiiti+++====;;=;;;;;=;;;;;;;;==+ittii+=+=;;;:,..,,.          ...,,,::;+tIIYYYYYYYIIIi;:,   ,:,.  ..   .,=tttIIIIYtt+:.,;+iiiii=;;;i+++iIYYIVVRRBMWRtBMMBBBBY          ......,,,..,,,.,:;=;===============+=+++=+++=++
VYYVYttIYYYYVVYYYVVVVXVVVVVXXXXXXXRRXRRRRRRRRRRRRRRRRRRRRRRRRRBBRRRRBBBRBMRVYYYIitttiittiiiii++++==;;:;;;;;=;;;;;;:=+++++iiti++==;::,..  .,:::=+tYVXXXVYYIttiiiiiiiittttIYYXBMMRt.       ,;+itIYXVVVYIiitYXVIYR#WBXRBBRXYi+==iIVXXMI:;=iIttVBBBRXRWR          .....,.,,.,,,..,:=================+==+===++++=
YttIIitIIIIYYYIYVVYVVVXXXXXVXXXXRRRRRRRRRRRRRRRRXRRRRRRRRRRRRRRRRRRRRRBBBBRVYYYIi==+itIItiitii+===;;;::::;;;;;;::::;==+==::;;===;,  .:=tYVXRXt=:...,,:;===iIYI=::::;;==;;:,.   ,tYYi+tYVRRXXYVXXBWBVIIIIYVRMBXYXRYi=+tYXXXVItIYVVXBY    ,.;YXXVVXXR#;          .......,,,,,,,,,;===;===========++==++++++++=
VItIYItttttIYYYYYYYYYYYYVVXXXXXXXXXXRRRXXXRRRRRRRRRRRRRRRRRRRRRBRRRBMMMBBBBXYIYYYtttiii+++++i+=;;==:::::::::::::;;:;;===++++==;::=iYRBMXI+,   .,:;;;;==;,,:;+tIIIt+=++++===;:=;  =VXIiii=;::;;::;+IVYttVXRRBMRRRRVi=;=tVXXVtiIVXXVMI...:;;tXRXXXVVXWX   .  .. .......,..,,,,,.,,;===============+++++++++++=
YIIIIIttIIIYYYYYYYVVYYYYVVVXXXXXXXXXRRRRRRRRRRRRRRRRRRRRRRRRBBBBW###W######WBVIYXBMMMBRVYIti+=;:,. ..    ...,,,:;;;;=++===++=;;;+IXXI+,  :=tVRRRBBMBBBBBBVt+;::;=+iiiii+====;;::,;i+;:,,.....,:iVVVItiiiVMMMMBMBVt=+iiittIt==iYXXVM+  ,:;:+XXXRRXVXRM=   .    ........,.,,,,..,.,;==================+++++++=
VYYYIttIIYYYIYVVVVVYYYYVVXXXXXXXXRXXXXRRRRRXXRRRRRRRRRRRRRRRRBMMY+:     ;+VBWWBBMRRRBBW######WWMMBRXVVYItii++=;;::::;::;==;;:;;=tYI;,=+IXRBRRRBMXVVY+,,;+IVYYt+;::,..,;+;;;:;tVXItt+:....,,,::.,tBMV+:::=itttIIt+:,:====+==::+YRRXX: .,:::tXRXRRXVXXWM;   . ..  ....,.,...,,..,.,,:;==;=================+++=
XVYYYYYYYVVVVVXXXVVVVVYYVVXXXXXXXRRRRRRRRRRRRXRRRRRRRRRRRRRRRMWt. .,,.     .+VW##RXYIIIYVVXRMWW##############WWMBRVYYi+iiIYYVXRRBBXiiVRXRMMRXRRRRRRVi,  .,:+YRRXVVIi;,:;:,..:iIIIt+;,:,,,,..,::  I#WI: ,        ,:=+=;:::;=::+YXXXI...,:::YRRXVXXXRVRM=      .  ....,,,..,,,,,,,,.,;+=;======+===++=====+++=
VVYYYVXXXXXXRRRXXVVVVYYYYYYVXRRRRRRXXXRRXRXRRXRXRRRRRRRRBRRBMV; iYVYYIti::,.   .i====itIt+i+++=;:,.::;=iIYXXMW###########W####WWWBBBMBXYtiIBWBXRBBVi,.,:,,,;=+=;:. .,;i+:=+tVXVIII+:,,,,,,.. .,;, tMR;  ,..:;=+iiiiii++++;:::;iXBX+...   ,VMXXXXXXXXXWV,   . .........,,,,......,..,;==================+=+==
VVYYYVVVVXXXXXXXXXXVVVYYYVVVXXXXRRXXXRRRXRRRRXRRRRRRRRBRBRRMRi:iIIt++iitt=:.....,++++itYYIItttti+;,    .....,,:;=+IXRRBBBXYYYVXXRRVttIIt++=iIYVYYt=,  ,::::::,...    ,;;:;=tRBBVVI=:,,,,,,,..,:::,;XWI  ,;;;==+=======iii=;;:;tVRY,    .;iRRXXXXXXXXXMV.   . . .......,........:,,,,:;=================+=+==
VVVXRRRBBBBRRXXVVVYYYYItIYVVXRXXRRXXRRRXXXXRRRRRRRRRRRRXBRMMV;=Ytiiittt+iiii=;,,.;=+==+tItIttttiitti+;:;;;:::::,.        .:=++;;+it: ,,::::.        ,:::;;:::::;;:::;==;:=+++++iIt=:,:,,,,,..  .:: :IRI:,;++===========;;+=:,:;++==tVRM##WBXXXXXXXXXVBX:        ......,,.,,,,,.:,.,,.,;=;;==+========+++====
VVVVXXXXXXXXXVVVVVXXXXYIIYVXXRRRRRRXXXRXXXXRRRRRRRRRRRRRRRMBt:+tiiiiiiiitiii+=;:.:;===+tIIttIIt++ii+=;::;;;;====;;;====+iiii+;::=iI+.::;:,:;;:;=====;:,,::::::;;;::::::::=+++==tIt=:,,,,,,,,.  ..::,;YRI: .::::,:::;;;;;;itItttIVRBMMBRRRRVXXXXXXXXXVRB=       .........,,,,,,,,..,,..;;====++=======++=====
XVVVXXVVVVVVVVVXXXVXVIiiIVXRRRXXXXXXXXXXXXXXXRRRRRRRRRRBRBBY:.ttiiiiiiit+=+++ii+;.:==++itttiiii+++=i+====;:;::::,,,,.,;;;:,...,,,=tI.:::,...,.,,::;;;;;;;=++i+==;;;;;;,,,:,,::;ti;:::,::,,,,,.  .,::,:iBMRVYYYYYVVVYYYVVVYYtt+:,:tXRXXXXXRXRXXXXXXXXVXW+  .     ..........,,.....,,,, .:;;;=============++=;
XXXXXXXXXXXXVVXXXVXRVIIVXRRXRRRXXXXXXXRRRRRRRRRRRRRRRRRBBMBi,:Ittttttttt==++iiti=,;=====itIi++iiiii+i++=;;:::::::,::,:::,,,::::;:=iY:.,,,..,,:;;;;;;:;;==;;=+=;:::::;;:,...:;+tt=:,,::::,,,,... .,,:::,.:====++ii+++==;;;;::;=;;;tXRXXXXXXXXXXXXXXXXVVWi  .  ..............,.......,,,.,:;==;==============;
XXXXXRRRXXXXXXRXXXRY+=IVVXXXXRRXXXXXXXXXXXXRRRRRRRRRRRBRRBBt:;tiiiittttt==+iiitt+:;=+++++ittiiiii+i++++==;;:,,,,.,,,:,,.,,,::,,:,,;Vi.,:;=++++==========;;;:,.  ......,;=iIYYYt;:;;;;::,,,:,,,...,,,:;=;,,,,,,,,:::::::::;;;;==;:+VBXXXXXXXXXXXXXXXXRVWI     ....................,,,,,,.,:;=================
XRRRRBRRRXRRXVXRRRXi:+VXXXRXXXXXXXXXXXXXXXXXRRRRRRRRRRBXRBMY;:ii++itti++=++i++iti=+++++++itiiiii++i+++++===:;;::,,,,,::,,,::::,,.  +RI, .,:::,,::,,..,::;;;:;;+tYYVXVVVYi+;;;;;,::::::::,::::,.  .,::;;;;;;;;;:::::;;;;;:;;=;==+=+YBXXXXXXXXXXRXXXXXRXMY,   .  ................,,,,,..,.,,:============+=+=;
RBBBRBRRRRXXVXRRRXIIIVRXVXXXXXXXXXXXXXRXXXXRRRRRRRRRRRBRBBMV=.==;;=ii+=;:;=++iiit=+++++=+iiiii++++i+=+=+++=====;:,,,,::,,,,,,,:,,,, ,tXXVVVYVVVVVVVXXXVYIttIIIIi==:,. .  ,:;::::::::::::::::,,,.  .,:;;;=;:::::::::;;;;;;;;;:;=+++iRRXXXXXXXXRRRXXXXXXMV:  .    ..............,,,,....,,,.,:=;;==========+=;
RBBRRRRXXVVVXBBXYtiYVVXXXRRXXXXXXXXXXXXXXXXRRRRRRRRRRRBRBBMBt.::;;;+iii=,:;=++=;;==++ii++=iiii++++++==+++++++==;:,.,::,,,,,:::,,,,:=;,......,,..,,.         ..   ....,,::;=;::,:;;:,,:::::,,,,:,....,::;==:::::,::::;::::;:=;::;:;+RRXXXXRXXXXRXXXXXXXBR+      ...................,,,,..,..,:;;;==========;;
BBRXXXXVVXRBRRVYttYVXXRXXXXXXXXXXXXXXXXXXXXRRRRRRRXRRRBRRRBMV,,=+===iii=,,.,:;==+t=;;+iii+iiii++i+++==+++++i++++=;,,,,,,,,,,,.,:;=+;;;:,,,,,... ..    .,,::::,,,,,,,..:;;::,,::::::::::::::::,,,....,:::=+=+++=;;;;;;;;;;;;++==;:;=RRXXXXRXXXXXXXXXXRVRMI.   . .............,..,,.....,.,,,.,;=;==========;;
RRRXXRRRRRRRVYIIVXXXXXXXXXXXRRXXXRXXXXRRXXXXRRRRRRRRRXBXRBBMBI ,::;=+ii=.::,,;+tRBY+=+i+=i+iti+==++++++++=+i=====;;;:,,,,,..,,;==;;:,,:::::::,,,,:,,::,...,,:,,,,,,,:;;;:,,.,,:;;:::::::::,,,,,.....,,:,:;;=iii+===;;:;;;:;;;;;;;::VRXXXRXRXRRRRXXXXXVXMV:      ...... ......,,.....,,,.,,,,.,;=;;;========;
XRRRRBRRRXVIttIYYVXXXXXXXXXVXXVVXXXXXXXXXXXRRRRRRRRRRXRXRRRBBRI ,::;itii,,::;+IVRRVt++tItiitti++=+i+++=++++i+======;,,,,,,,,:=;::,,:::,,,,,,,,,,,..         ..,,:,::;;:,,,,,::;;;;:::::::,,,,,,.   .,,,::::,,,::,,,,,....,,,..,,;;;VRXXXXVXXXRRRXXXXRXXBY,      ........,,...........,,,,,,...,;=;;;======;;
RRBRRXVYIIIIYVXXXXXXXXXXXXVVVVVXXXXXXXXXRXXRRRRRRRRRRRRRRRRBMWWt .:;+tii:,,::=IXRRXYtittit+itti+==++++++++++++====+=,....,:;==,,,::::,,::,,,,,,..           ..,::;;;:,,,,:::;;===;:::::,,,,,,,,.   .,,,,,::;::,...,,,,:,,,,,,,,,,:=XBRXXXXRXRRRRRXXRRXRBI.       .............,,,,...,,.,,.,,..,;;;;;=====;;
XRXXVVVYYYVXVXXXXXXXXVVVVVVVVVXXXXXXXXXRRRRXXRRRRRRRRRRRRRRRBBWW,  .;iti. .,,=YRRVVYIti++t+ittti+=+++i+++++====++=+;....,:==;::::::,,::::,,,,,.....     ..,,,:;;=;;:,,.,:::;=====;:::::,,:,,,,,,.   .,,,,::;;;:::::::::::,,::::,:,=XRXXXXXXXXRRRXXXRXXXBY,       ............,,,,,,.....,.,,,,.,,;;;;;====;;
BRRVYVVVVVVXVVVVVVVVVVVVVXXXVVXXXXXXXXXXXXRRRRRRRRRRRRRXXRRRRRMWMt. .=II,,::;iVXVVVIti+;;+++itti==+++++++++=+==++=;:,.:;=;::,,,:::::::::::,::,,. ..,,,,,::;==;;;:,.,,,:::;;;;;;;;;:::,,,,::::,,,    .,,,::,:;;;;:::,,,,,::,:::::::iRBXXXXXXXXRRXXXXXXRXBRi      ........ ...,. ........,,.....,, ,:;;::==;;;
BRXVVVVVVVVVXXVVVVVVVVVVVVVXXXXXXXXXXXRXXXXRRRRXRRRRXXRRRRRRRRRBWWi  ;iV:,::=tXVXVYi==+===iittti++=++i+++++===+==;:::::;=;:,,:,,,,::::,:::::::::,.,,,,,::;;:,,.,,,,,,,:;;===;;;;;::::::,,::,,,,.    ...,:::,:::::::::::::;:::::::=IRRRXXXRXRXRRRRRXRXXXRBI.       ..................,,,,,,,,,,,,.,,:;;:;=;;;
RXVVXVVVVVVVXXVVVVVVVVVVVVVVVXXXXXXXXXRRXXXRRRRXXRRRRXRRRRRRRRRBBWR+,,=Y;.,:;=i+i+++===:;++itttiii+++ii++++======;;;====;;:,,,:::::::::::::::,,,,,,,,.,........,,,::,::===;;,,,:;;:;;::,,,,,,,,.   .,::,,:::;;:,::,,,,:,,:,::::::=YRRXXXXRXRXRRRRRXRXXXXBV;      ............. .......,.,........,.,:;;;;;::
XVVXXXXXXXVXVVVVVVVVVVVVVVVVVXXXXXXXXXXXXXXRRRRRRRRRRXRRRRRRRRRBRMWRi,:I=.,;=;:,,==+ii=::=+itttii+++++++++++++===;==++=;::,,,,,::;;:;::::,,,,,..... ........,,,,,,:::::==;;::::;;;===;;:,,....,....,::::,,:;;;::::::::::::,::::::+VRRXXXVXXRXRRRRRXRXXXXMR+  ................. ........,.........,..,;;;;;::
VVVXRXXXXXXXVVVVVVYVVVVVVVVVVVXXXXXXXXXXXXRRRRRRRRRRRRRRRRRRRRRBRBBWMt,=i..;==;:,  .;+i=::+itiiii=++++iiii++++=====;=::,,,,,,,::;::,............... ...,,,,,,,::,,::::;==;:::,..,,,::;=++++;;:::::::::::,,:;;;::;:::::::::::::::;tRBRXXXVXXRXRRRRRXRXRXXBXi    ............ .....................,. .::;;:::
VVVXXXXXXVXXVVVVVVYYVVVVVVVXVVXXXXXXXXXXXXRRRXRRRRRRRRRRRRRRRRRBRBRBMRi;i;..:;;:;:;=+IYI+:;+iiitt+ti+++iii++++=====;::,,,,,,,,,,,,...,,,...,,,,,,,,,,,,,,,.,,,,,::::::;===;:::,:;;;::,,,:;==+=:::::::;:::;;=;;:::::::::::::::;::;IRBRXXXXXRRXRRRRRXRXXXVRRt     ..............................,......,.:;:::
XXXXXVVXVVVVVVVVVVYYVVVVVVVXVXXXXXXXXXXXRRRRXXRRRRRRRRRRRRRRRRRRRBBRBMMYti:..,::;;+itYRBY=;iiitItitt+==++ii+++=====;;;;:,,,,,,,,,,,.,,,,,,,.,,,,,,,,,,.,,,,,,,,,::::::;++=;;=iYB#####WBVt+=;;=+=;:;;;;;;=+=;;;;;:;;;;:::::;::;::;IBBRXRXXXRXXRRRRRXRXXXVBBI     ....,............ ..,................  ,;::,
XXXXXXXXVVVXXVVVVVVVVVVVVVVVVXXXXXXXXXXXXRRXXRRRRRRRRRRRRXRRRBBRRRBBBBB#tiiti===;,,.,=YRRV+++iitii+ii+++ittii++====;:;;::::::,,,.,,,....,,,,,,,,,,,.......,,,,,:::,,::;ti====iIVXRBBMMBXVYIi+==;:;===;;;==::,::;:::::::::::::;;:=YBRRRRRXXXXXXXRRRRRRXXXBRt   ......,...         .. ...................   ..
XXXXXXVVVXXVVVVVVVVVVVVVVVVXXXXXXXXXXXXXXXXRRRRRRRRRRRRRRRRRRRBRRRRRBBBMMViiIYIti::,...:=t++++itii+iiiiiiiiiiii+==;;;;:::,,,,,,,,,,:,,.,,,,,,,,.,,,,:::,,,,,::::,,,,,,:tYti+==+++iiii++=:+IIt======;;;;==;::::::;;::::;::::;:;;;+VBXRXXXXXXXRRRRRRXXRXXXBXi   .......             .. ,  .........     ..    
XXXXXXVVVVVVVVVVXXVVVVVVVVVXXXXXXXXXXXXXXXXRRXRRRRRRRRRRRRRRRRRRRBBBBBBBBWY:,;iIIt+:,...,;iiiiitttttttii++++iii+==;;;::::,,,,:,,:::::,,,.,,,,,,,,,,,,:::::,,,:::,,.,,,,iIYYItti++=====++==+++=;======+iYt+;:::::;==;:::::;:;;;;;+XBRRXXXXXXRRRRRRXXXRRXXBV;   .....    =YRMW#WWW=   . ............          
XXXXXXXVXVVVVVVVVVVVVVVVVVXXXXXXXXXXXXXXXXXRRRRRRRRRRRRRRRRRRRRRRBBBBBBBRMMXi,,i+i+==;;:=+iiiiiiiiiiiii++++tiii+===;;;;=;;:::;::::::,,,,,,,,,,::::,,,,,,,,:,::,,,,,,:,,:=itIIIIIttiittiiii++++=+++itIYYI+:::::;::;===;;;;;:;;;;=tRBRRRXXXXXRRRRRRRRXRXXRRI.  ......  ,VBMBRRRRRWMt   ............ ..,,.     
XXXXXXXXXXXVVVVVVVVVVVXXXXXXXXXXXXXXVXXRRBBRRRRRRRRRRRRRRRRRRRRRBBBBRRRBBBBWMI;=;:::::::;===+iiiiii++iii+++ti++=+++=;;;;;;;::::;;;::::,,,,,,,,,:::,,,,,,,::::::,,,,:,,,,,,:;=+ittttiii+++iii+++ittIYIti+;,,::::::::;===;==:;=;;;tRRRRRRXXXXRRRRRRRRRRXVBBt   . ...   IMBRXXXXVXVMWI       ........          
XVVVXXXXVVVVVVVXXXVVVVVVVVVVVXVXXXXXXXXXXRRRRRRRRRRRRRRRRRRRRRBBBBBRRRRBRBRBMWRt,,:;;;;;;:;;=ittiiiiiiiti++++ii+++i+;;;;::::,,,::;;;::::::,::,,,,::::::,,,,:::::::::::::,,,..,:==ii++iii+++iiiiitIIIIt+=:,::::::::::;=+=;===;;;=IRRRXXXXXXXRRRRRRRXRXXRBY:   ...... .BBXXXXXVVXXXBBI ..                   ;B
XXVXXXXXXXRXXXXXXXVVXXXXXXXVXXXXXXXXRXXXRRRRRRRRRRRRRRRRRRRRRRRBBBRRRRRBBBRBBMBXI:::===;;::;++ittt+iiiiiii+iiii+====;=;;;;;;::,,,,,,,,,,,,,::::::::,,:::::::::,,,,,,,,,,:,,,,,,,:=++iiiti+iiiiitIIIIttti=;;:::;::;==;:;==;;;;==+IRRRXRXXXXXRRRRRRRRRRXXRI,  ....,,. ;MBRXVXXXVYVRRRW###BBXVIt+=::,        IM
XXXXXXXXXXXXXXXXXXXXVVXXXVXXXXXXXXXXRRRRRRRRRXRRRRRRRRRRRRRRRRRBBRRRRRRBBBBBBBMMWXt=;;;;;:,;+iiittii+++ii+++=+++===++==;::;;;:::;:::;;::::::::::::::::::;::,,,,,,,,,,,,,::,,,,,.,:=+iItIttttttiittttttii+===;;;==++=;;=;;;:;==;+YBRRXRXXRXXRRRRRRRRRXVXMV:    .... :VMXXXXXXXXVXRRM#Rt;=tIVRMW########Xi+iXM
XXXXXXXXXXXXXXXXVVXVVVVXVVVXXXVVXXXXXXXXXXXXRRRRRRRRRRRRRRRRRRRRRBBBBRRBBBBBRRBBMWMBXYi==;=tYYtiititiiiiii++++++++++++==;;;;;::;==;;==;::::::::::::;:::::,,,,,,:,,,,,,,::::,::;:;==++++ittttttIiiiitti====ii+=++ii+=;===;=:;=;;+YBBRXRXXXRRRRRRRRRRRXVVRY,    ...  ,V#RXXXXXXXVVBWBt                 .,.  YM
XXXXXXXXXRRXXXXXXXXXXXVVXVXXXXXXXXXRXXXXXRRRRRRRRRRRRRRRRRRRRRRRRRBRRRRBBBBBBRRRRBMMWWMMBVYYVYIiiiitiittiiii+++++=+==++=;;;;;;:;;:::::::::::::::::;;:::,,,,:::,,,::::::::::;======;::==iIIIIIItiiiiii+;;==+ii++ii+++======;==;;iVBRRXRXXXRRRRRRRRRRRXVXMV:   ,.,,:::+###MMBBBBM#WY:  ..,  ....   .     .  tM
XVVXXXXXXXXXXXXXXXXXXXXVVXXXXXXXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRBBRBBBBBBBBBBRRBMMMYIttiiii+tiiiiii++++++==++++====;;;;;::::::::::::::::;;;;;::,,,,,,,::,:::::::::;;;;;;;;;===;::;iIItttiii++==;:;::;=====++=+==;;;=;==;=tXBRRXXXXXRRRRRRRRRRRRVXBI.       .,  .:;iVBBRXBV=  ,.,,,,,,,,,,,,....     iW
RXXRRRRRXXXXXXXXVVVXXXXXXXXVXXXXXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRBBBBRBBBBBBBBBRBBBBBBXtttttti+Iiiitttiit+++===+======;;;:;::;;;;;::;::::::::;;::,,,,::;;=====;:,:::;;;;;;;;:::;=;:,,=tYYItti+=;::,:::;;;;;=+ii+=;;==;;===;=tXBRRRRXXRRRXXXXRRRXXXVRBi           ... .,:;::=;. .,,,:,,,,,,,,,.::;=++++;iX
RRXXRRXXXXXXVXXXXXVXXXXXXXXVXXXXXRRRRRRXXXXXRRRRRRRRBRRRBBRRRBBRRRRRRRRBRBBBBBBBBBRBBBRBBBItIttttiiiiiittttti+==;====;;;;;;;;;;;;;;::::::::::::::,::,,,;=++++====;;;;;:;:::::::::::,::,,,:;;;:,:,,,,,::;::::;=iIIt+====;;;=+;;+YRRRRRRXRRRRXRRXRRRRRRXMB=          .:;:;;:,....,,,...     ...,,::::;=+itti+=
RRRXXXXXXXXXXXXXXXXXXVVVVVXXXXXXXXRRRRXXRRRRRRRRRRRRBBRRRRRRRRBRRRRRRRRRRBBBBBBBBBBBBBRBBMYIttiiti+tiiitiiiiti+====++;;;=====;;;;;::::::::,:::::::::,::;;=+==;;=;::::::::::::::::::,,;==:,,...  .,,:::;::,:;=tYYi+=;;=;;;;==;;+VBRRRRRRRRRRRRRRRRRRRVYRV:                  .,,,,:;:,,,.,,,,,,..........,::;;
RRXRXXXXXXXXRRXXXXXXXVVVVXXXXXXXXXRXXXXXRRRRRRRRRRRRRRRRRRRRRRRRRBRBBBRRRBBBBBBBBBBBBBBBBMRIttttti+i++iittiiii++==;;=;;;=====;;;;::;:::,,,,,::::::::;===;;;;;:;;::::::,,,,,,,,,,:;=+++ii+;;;;==itYYVVVVVVVVYIi+=;;;=========;=IXBXRRXXXXXXRXXRRRXXRRBXRX+                                  . ....  . ..    .
RRXRRRRRRRRRRRRRXXXXXXXVXXXXXXRRRRXRRRXRRRRRXRRRRRRRRRRBBBBRRRBRRBBBBBBBRBBBBBBBBBBRRBBBBBMIitIttiiiiittttiiiiii+=;;==;;::;;;;;;:::::::::,,,:::;:,:;;======;::,:::,,,,,,,,,,,;=++itIYYIIVVVVXRRBMBBXXXXXRBRY+;,:;:==+=;;;=;;=iYRBXXXRRRRRRRXXRRXXXXRXXRMI                                               .,.,
RRRRRRRRRRRRRRRRRRRXXXRRRXRRRRRXXXXXRRRXXXXRRRRRRRRRRRRRBRBRRRRRRBRRRRRBRRRRBBBBBBBBBBBBBBWVIItttIti+++tIItti+ii+;==;;;;:;;;::::::;:;:,,,,,,::::::;;;;;==+tYXVYt+=;;=;;=+iittIYVXXXXRRRXRRRXVYI+:::::::::;;:::,,:::==;;;;+=;=IXRRRRRRXXXXXXRRRRRRRRRRRRRXI+=;:,.                                            
RRRRRRRRRRRRRRRRRRRXXXXRRRRRRRXXXXXXRRRRRRRRRRRRRRRRRRBRBRRBRRRRRRRRRRRBRBRBBBBBBBBBBBBBBBMXYtttIIti+++iiiittttti===;=;;;;;;;;::::::::::::::::::::::;;;===+tXMWW##WMMMBRBRRRRRXYIti+=::::::,,...,::::;=+++==;::::::;=;;;;;:=iVRRXXRXXXXRXXXRXXXRRRRXXXXRXItIYVVVVYYIIti+;:,                                 
BBRRBBBBBBBRBRRRRXXXXXXRRRRRXRXRRRRXRRRRRRRRRRRRRRRRRRBRRBBBBRRXRRRRRBRBRBRBBBBBBBBBBBBBBBBBXIitItttttiiiitItiiii=;;;==;;;;;;;;;:::;;:::;::,,,::::::;;;;::,.   .;+tYVXXVVIti==;;::,.,:::::::::;;;==;;==+=;;;;;;::,::;;;;;=:=IXRRXRXXXXXRXXXXXXXRRRRXRRRRXI+iitttIIIIYIVVVVXXVVYIItii+=:,.                   
BBRRBBBBBRRRRXXXXXVVXXRRXXXXXXXRRRXXRRRRRRRRRRRRRRRRRRBRRRBBBRRXRBBBRRRBRBRBBBBBBBBBBBBBBBBMRYittitttiiiiiiIti+ii+======;;;:;;;;;====;;,,:::,,,,::::;;:::,,,,,,.     .,:;;;;====++============;;;;======;:::;;;::::;;;;==;:+VRRXXXXXXRRRRXXXXRRXXXXRRRXRVI++iittttttttIttttIIIYYYYVVXXXXXXVVYIti+=;:,.      
BBBBBBBRRRRXXVVXXXXXXRRRXRRRXXRRRRXXRXXRRRRRRRRRRRRRRRRRBBBRRRRRBBBBRRRRBBRBBBBBBBBBBBBBBBBMBXItittItiiitiitttiti+ii=+++==;;;=;;;;;=;;;::::::,,,,,::;:,,,,::,..,,,,,,,.,,:::,::;;;;;;;;;;;;;;;;=;====;;;;;;=====;::;;;;;;:;IRBRRXXRRRRRRRRRRRXXXXXXRXRXRVI+itiittiiiiitttiiittItttttttttIIIIYYVVVXXXXXXXVVYt
BBBBBRRRRXRXXXXXXXXXXRRRRRRRRXRRRRXXRRRRRRRRRXRRRRRRRRRRRRRRRRRRRBBBRRRRRBBBBBBBBBBBBBBBBBBBBRYiiItttiittiiiiiii+=+=;;;;;;;::::::::;::::;;:,,,,:,,,::::,,...,,,,,,,,,,,:::,,::::::;;;;;======;;;;;;;;;;:::;;;;;;:;:;;::;;:=YRBRRRRRXXRBBRRXXXXXXXRRXXXXXXI+=++iitttttttttttttttitttIIttIttttttttIIIIIIYYIYYY
BBBRXRRRRRXXVVXXRRRRXRRRXXXRRRXXXRXXRRRRRXXRRRRRRRRRRRRRRRRRRRRRRRRBBRRBRBBBRRRBBBBBBBBBBBBBBBXtitiiiiiiiiii+iiiiitii++=;;;:;;;;;::=;;:::::::::,:,,,,,:::,,,,,,,,,,,,,,:::::::,:::;;;:;;;;;;::::::::::::;;;;;;;;;;;;=;;=;+YXXRRRRXRRRRXXRRBBRXRM########WXItVIYYYYIItiiiiiittItttttttttYItttttttttIIttIItItt
BRRXXXXXXXXVXXXRRRRRXXXXRXXXXXXXXXXXRRRRXXXXXRRRRRRRRRRRRRRRRRRRRBRRRRBBBBRRRBBBBBBBBBBBBBBBBBRYttittttiiiiitttiiiii++=======;;;;;;;;:;;;:::;::,,,,,::,,,,,,,,..,,,,,,,,:::::::,::,,,,,,,:::::;;;;;;;;;;;;;;;;;;:;:;;=++;I##WRRBMM############MY=:,,::;;==;,.,;==+tVXXRXVYIIItittttttttIttttttttIttIttIItItt
BBBRRRXXVVVXXRRRRXXXXXXRRXRRRRXXXXXXXXXXXXXRRRRRRRRRRRRRRRRRRRRRRBBBBBRRBRRRRRBBBBBBBBBBBBRRBMBXItittttii++itiiiiii+======++==::;;;:::;;;;;;:,,:::::;;;::,,,,,,,,,,,,,:::::::::::::::::;;;==;=+===++==;;;;;;;;:::;;;;=+=.  I######X=  .:,                               =IXXXXVYtiiIItitttttttttItIIttIItttt
BBBBBBRRXRRXXRRRRRXXXRRRRRRRRRXXXXXXXXRRXRRRRXXRXXRRRRRRRRRRRRRRRBBBBRRBRBBRBRRBBBBBBBBBBBBBMMBXIttiiiiiiiiiittiiiii++i+==;;====;:;===;::;;;:,,,,,,,,,:::::::,,,,,,,,,,,,,,,,::::;;;;;;==+++i+++===;;::;;;;;;;:;;======,                                                     .;tXXIiittYttttttttIttIttIttttt
RBBBBBBBBRRRRRRRXXXXRRRRRXXXXXXXRRRRRRRXXXXXXXXXXXRXRRXXRRRRRRRRRRRRRRRBRRBBBBRRBBBBBBBBBBMBXYIYVItittttttii+iiiiii++=====;;;===;;;;;;;;;;::::,,,,,,::::::::::,,:::,,,,,,,,,:::::::;;;:::;=++iii===;;:::::;;::;;;;;;==;                                                          iXYIiittttttttItttIttIttttt
XRBBBBBBBBBRRRRRXRRRRRRRRRRRXXXXRRXXXXXXRRRRRXRRRRRRRXRXXXRRRRXRRRRRRRRRRRRRRRRBRBBRRBBBMMBIiiYXRIitiittt+++++++iii+iiii++====;;;;;;=====::;;;;;;;:::::,,,,,,,:,,,,,,,,,,,,,,,,::::::::;;;;;+++=;:,,,::::::::;;;;;=;++,                                                            =BVIIttttttItttIIIIIIIItt
RRBBBRBBBRRRRXRRRRBRRRRRXXXRXXXXRXXXXXXXXXXXRXXXRXXXXXRXXRRRRRRRRRRRRRRRRRRRRRRRRRBBBRMWWVIitIVXXItiiiiiiii++iii+iiiiiii++++++==;;;;;===;::;;;:::;;;:,,,::::,,,,,.,,,,,.,,,,:,,,,,,::::;;:,::;;::::::::,:::::;;;==iit=                                                               iXXVtitiiIiIttttttttttt
RBBBBBBBBBBBRRBRBBBRRRRRXXRRXXXXXXXXXXXXXXXXXXXXXXXXXXRRRXRXRXXXXRRRRRRRRRRRRRRRRBBBBWWR= iYVVVXRVtitii+iii++ii+++ii++++++++=;;=====;;:;;;::;;::::;;=;:::::,,,,,,,,::::,,,,,,,,,,,,,,,,,,,,...,,,,,,,,,::::,,,::===+i:                                                                 .iVYtIIiVittttttttttt
RRBBBBBBBBBBBBBBBRRRRXRRRRRXXXXXXXXXXXXXXXXXXXXXXXXXXXRXXRRRRXXRRRRRRRRRRRRRRRRRRBBRMMY. .=IYYVRRViiti++iii++++++=+++++++++i++++=;;;;;;;=;;;;;;;:::,:::,:::,,,,,,,,,,,,,,,,,,.,,,,,,,.........,,,,,,,,.,,:::::;;=;;++,                                                                    tXYt+itItIIItttttt
RRRBBBBBBBBBRRRRRRRRXRRRRRXXXXXXXXXXRXRXXXXXXXXXXRRRRRXXXRRRRRRRRRBRRRRRRRRRRRRBRRBBWV   :;IVVVRBRYii++iii+i++++++==+++ii++++++==;;;;;;;:;;:;=;;;;;;;:,,,:::,:::,,,,,.,,,,,,...........,,.......,,,,,,,,,:::;;=+=;+i:                                                                      ;VViIttItIttttttt
RRRBBBBBBRRRRRRXXRRRRRRXRRRXXXXXXXXXXXXXXXXXXXXXXRRRXXRRRXRRRXXRRRRRRRRRRRBBBBBRRRRB#Y   .;iYVXRBXYii++iiti+++++==+===+ii+++====+==;;;::::;;===;;;:;=;:::::;;:::::::,,,,:,,.....         ,,,,,,.,.,,,,,::::;;;;;;;t+.                                                                       ,WRitItttttttttt
RXXXXXRBBBBBBBBBBBRRBBBRRRRXXXXXRXXXXXXXXXXXXXXXXXRRXXXXXXXXXRRRRRRRRRRRRRRRRRRRRRBMM+   ,=iIVXRBRXItiii+++++i+++++++==++====;==+++=;;=====+==;:;;;;;;::::;;;:,,:::;;;:,,,,,,:::,.,.,,,,,,,,,,,,,,,:::,:::;;==++=+t,                                                                          +MYtttttIiittt
RRRRXXRBBBBBBBBBBRRBBBBBRRXXRXXXRXRRRXXXXXXXXXXXXRRRRRXXXXXXRRRRRRRRRRRRRRRRRRRRRRBMM=    ,iRBRRBRXYti+i+==++==+++==+=============++====;====;;;=+++=;;=;::::,.,,,,:;=;,,,,,,,::,,,,,::,...,.,,,,,::::::::;;=+++;tI.                                                                            YXYttItiIitt
VXXVVVXXRBBBBRRBBBBBBBBBBBRXXXXXRRRRRRXXXRRXXXXRRRRRXRXXXXRRRRRRRRRRRRRRRRRRRRRRRRBMWY.     ;XWWRVVXt+=++++++===++==++++=====++=====;;;;;;;;=======;:::;::;=====;:::::;;::,,::,,,,,:::::::::::,,,,,::::::;;===+++II.                                                                             ,tRVititttt
VVVVVVXXRBRBBBBBBBBBBBBBBBBRRRRRRRXXRRXXXXXXXRRRRRXXXXRXXRRRRRRRRRRRRRRBRRRRRRRRRRBBWY,.      i###XXIi++++++++++++++i++++++==+=====;;====;;;==+==========;:;;;;=;;;;:;;;::,,:::,,,,,,,::;;;::,,::::::;;::;==+++it+;                                                                                ,tBViIiit
YYIIYYVXXXXXRRBBBBRBBBBBBBRRRRRRRRRRXRRXXXXRRRRRRXXXXXRRRRRRRRXXRRRRRRBBRRRRRRRBRBBMR+.,.        Y#WXI+====+====;==++==+ii+==+=+++==++==;:::;==;==;=++======;::;====;;;;;;;;;====;::::::;::,,::::::::;===++++iiii                                                                                    .XVYtti
YIIIYVXXXXRRRRBBBBBBBBBBBBBBBBBRRRRRRRXXRRRRBRRRXXXXXXRRRRRRRRRRRRRRRRRBRRRRRRRRRBBMY:.:,         .YWWV+;====+++++++++++=====+++++++++========;=;;;;=;;=+++====;:::;;=;;;;;;::;::;;==;;;;::::::;;:::;===+i++++ii:                                    .                                                 ,IVIi
IIYVVXXXXRXRRRRBBBBBBBBBBBBBBBBBRRRRXXRRRRRBRXXXXRRRRBBRRRRXRRRRRBBBBBBBBBBBBBBBBBMR+. ..            tMWV=,;==++======+++++==+=+++++++++++++=========+===++==i+=;;;==++=;;=;;;;;;===========+=;;;==;==+=+i++++++.                            .......  .                                                  ;VY
IYVVXXRXXXXRRRRXXXXXRBBBBBBBBBBRBRRRRRRRRRRRRXXRRRRRBBRRRRRRRRRBBBRRRBBBBRBBBBBBRRBBI,  ..             ;YRI=;;;=====+====+++++==+++++iiitti=;==+=;;;;;==+++==++==;=+++=;;==+==++==+++=========;::;====+++++itYXX+                                 ....                                                     t
VVXXXXXXRBRRRRRXXVYVXRBBBBBBBBBBBBBBBBRRRRRRRRRRBBBBRRRRRRRBBBBBBBRRBRRRRRBBBBBBRBBWMI,                  ,tYIt+=;===+===++++++++++iiiiiitttiiii+++==;;;;;;=++=======++++===++++=====++++++==;;;;;=====+iittIVXRBI                               .                                                           
VXRRXXXRRRRXXXXVVVVXXRRBBBBBBBBBBBBBBBBBRRBBBBRRRRRRRRBBBBRRRRRBRRBBBBBBBBBBBBBBBBRBWBi                     ,=tYIii+========++++++itiiiiiitIYItttttttii+;;:;=++===+++++++++++++++++++++++=++++=++==++itIt+;=iYVXV:                                                                                          
XXRXRRRRRXXVVVYVVVVVXXRRRBBBBBBBBBBBBBBBBBBBBBBBBBBBBBRRRBBRBBBBBBBBBBBBBBBBBBBBBBBRBMX=                        ,+IVt++=======+++++i+itiiittttIIIIYYIYYYYIi+==:,:=+====++++++++++iiti+ii++++i+==+ittti+;;:::;iVRV;,.                                                                                        
XXXRRXXXXXXXVVYYVXXXXRRRRRXXXXRBBBBRRRRRRBBBBRBBBBBBRRBBBBBBBBBBRRBBBBBBBBBBBBBBBBRBBWWX.                          .+XRXYti==i+===++=+ittttttIIIYYYYYYYYYVVVVVIi++=;;==+++++====+++iiitiii++++iiitti+;:;::;:,;tVY;.  .                                                                                      
XXXXXXXXXVVVVYYVXRRRRRRRXXVYYVXRRBBRRRRRRRRRRRRRRRRRBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBRBBBMV                               ,iVBRIiIt++ii++iiiiitttttIIIIYYYYYIIYYYVVVVYIItii++++iiittttttttIIIItttti==;;;==;::;:,:+IV+.                               :;                                                        
XXXXXXVXXVVYYYYVRRRRXRRRXXVVVYVXRBBBRRRRRRRRRBRBRRRBBBBBBBBBBBBRBBBBBBBBBBBBBBBBBBRBBMWV                                  .iRBBXVIItii++iitttItttIIIIIIIIYIYIttIYIYYYYYYYYYIIYYIIIIIIttttttii+====+==;;;::::,,;iYI:                               ,:;;;;:.                                                  
XXXXVVVVVVVYVVVXRRRRRRXXXXVVVVXXRRRRRRRRRRRRRXXRRRRRRRBBRRRBBRBBRRRBBBRRBBBBBBBBBBRRBMRi                                      :iYRXVVYYItttIIYIIIIIYIYIYYIIIIIIIIttItttttttttttiiiiiittiiii+++i+=====;;,,::,,,,;IVi                               :;,,.,,,,..,                                              
VVVXVVYYYYYYVXXXRRRRRXXXXVVVVVXXRRRRRRRXRRRRRXXRRRRRRRRRRRRRRRRRRRBRRRRRRRBBRRRRRBBRBBY;                                         ;iIXXXXXVIttIIIIIIIIIIIttIIYYIIIIttttttttIItttiiiiiiii++++++++=;;;;;::,,,::,,,,=VRi:,.                           ,  ....,,.                                                
VVYVYIIYYYYVXXXXXXRRRRXXXVVVVXXXRRRBRBRRRRRRRRRRRRRRRRRRRRRRRRRRRBBBBBBBRBBBBBRRRBBBBMV:.:.                                            =YM#WBXVVYYIIIYYYIIIItttIIIItIIttttIIttttiiiiiii++=+=+++=====;;::,,,,,...:iVi:,.                           ,:.,..,,,                                                 
YYYYYYYVVVXRRRRRRRRRXXXXXVVVVVXXRRRRBBRRRRRRRRRRRRRRRRRRBBBRRRBRRBBBBBRRBBRRRBBRBRBBWWY,.                                                   ,iYXXVVYItIIIIIIIttttttIttttttttttiiiiiiii+++++++====;;;;:,,,,::..   ,+;.                              . ...                                                    
YYYYYVVVVXXRRRRRRRRRXXXXXVVVVXXXXRRRBBRRXRRRRRRRRRRRRRRRBBBRRRBRRRRRRRBRBBRRRBBBBRW#WX+.:                                                       ;tXBRXVYIttttItttttItttttttiiitttiiiii++++++======;=;:,..,,,......=i;                                                                                       
YYYYYVVVVXXXRRXXRRXXXXXXXXVXXXXXXRRRRBBRRRRRRRRRRRRRRRRRRBBRRRBBBRBRBRRRRBBRRRBBM#W=  ::.                                                           .=tYVVVYIIIIIItttttiiiiiiiiiiii+++++++==;;;;===;:,..,,,,.    .:=:                                                                                       
YVVVVVXXXXXXXXXRRXRXXXXXXVVXXXXXRRRRRBBRRRRRRRRRRRRRRRRRRRRRRRRBBRBBRRRRRRBBBBBM#W=  :=,,..                                                             ,;+itYVYIttttttiiiiitiiii+++++++++==;;;;=+=::,...::,.    .:=:                                                                                       
VVVVXXXXXXXXRRRRRXXXXXXXXXXXXXXXXRRRRRRBRRRRRRRRRRRRRRRBRBBBBBBRRRRRRBBBRBRRBRM#V        ..                                                                  ,;itIYYYYIItiiiiti+ii+++++=+=;;;;;;;==;:. ...,,..   ,,i;.                                                                                      
VVXXXXXXXXXXXRXXXXXXXXXXXXXXXXRXXXRRRRRBRRRRRRRRRRRRRRRRBBBBRRRRRRRRRBBRBRBRB##Y                                                                                   .,;+IYYYItti+i++=++++=;;;;;;=++=;:,...,,,,... ,,i=.                                                                                      
VXXXXXXXXXXXXXXXXXXXXXRXXXXXXRRXXXXRRRRRRRRRRRRRRRRRRRRRRRBBRRRRRRRRRRBBRRBBWMi                                                                                          ,=iIYVIti+ii===;;;==;:;;;:,,.. .,,,,... ..;:.                                                                                      
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXRRRRRRRBRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXMWI                                                                                                .,;iIVVYIi+++=;;===:::,.  .......  ..=;.                                                                                      
XXXXXXXXXVXXXXXXXXXXXXXXXXXXXXXXRRRRRRRRBBBRRRRRRRRRRRRRRRRRRRRRRRRRRRBRBRM#X,                                                                                                           ..:=====:,,.. ........  .:=;.                                                                                      
RXXXRXXXXXXXXXXXXXXXXXXXXXXXXXXRRRRRRRRRBBRRRRRRRRRRRRRRRRRRRRRRBRXRBBRBW##B:                                                                                                                  .;;,..   ......   .;;,                                                                                       
XXXXXXRXXXXXXXXXXXXXXXXXXXXXXXXXRRRRRRRRRRBRRRRRRRRRRRRRRRRRRRRXRXBBXXM#W;                                                                                                                        .,.   .....   ..;:                                                                                        
XXXXRRRXXXXXXXXXXXXXXXXXXXXXXXRRRXXXRRRRRRRRRBRRRRRRRRRRRRRRRRRRRRRXB##Y                                                                                                                             .. .. ......,;;.                                                                                       
XXXXRRRRRRRRXXXXXXXXXXXXXXXXRXRRRXXXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXW#I                                                                                                  .                             .... .. ...,==:                                                                                       
RRXXRRRXRRRRXXXXXXXXXXXXXXXXXXXXRRRRRRRRRRRRRRRBRRRRRRRRRRRRRRRRXRW#t                                                                                                                                    ....  ..,;=,                                                                                       
RXXXRRXXXRRRXRXXXXXXXXXXXXRRRXXXXXXXRRRRRRRRRRRBRRRRRRRRRRRRRRRRB#M;                                                                                                 ,;..,,,,                             .,.   .,=+:                                                                                       
XXXRXRXXXXXXXRRRXXXXVXXXXVXXXXXRXXXXRRRRRRRRRRRXRBRRRBRXBBRRRXBM##i                                                                                                 .=;::::,:::,.                           ..,...;i;                                                                                       
RRRRRRRXRRRRXXXXRRXXXXXXXXXXXXXXXRXXRRRRRRRRRXBRRRRRRRRRBRRM####V=                                                                                                  .. :==;::::,,..                           .,..,+;,.                                                                                     
RRXRRRRXXRRRRXXXRRXXXXXXXXXXXXXXRRRXRXXXRRRRRRRRRRRRRRRXM###X:                                                                                                   ...       .,,::::,,.                           .,,+;,.                                                                                     
XXXXXXXXXXRRRRRXRXXXXXXXXXXXXXXXRXXXRRRXRRRRRRRRRXXBW####R:        .:,                                                                                           ,.            ..,:;:,.                           =V+                                                                                       
XXXXXXRRXXXXXRRRRRRRRRRXXXXXXXXXXXXXRRRRRRRRRRRRBW##WI:          .=i=,                                                                                                               .,,..                         iI;                                                                                      
XXXXXXXXRRRXXRRRRRRRRRRXRXXXXXXXRXXXRXXRXXRRRBB##Bi                                                                                                             .                         .                         :=:                                                                                     
XXXXXXXXXRRXXRRXRRRRRRRRRRRXXXXXXXXXRMRRBBBRRW#V                                                                                                                                                                                                                                                            
VVVXXXXXXXXXXXXXRRRRRRRRRRRRRRXXXXRRXRXRRRB##M                                                            ,,.                                                                                                                                                                                               
VVVVXXXXXXXXXXXXRRRRRRRRRRRRRRRXXRRRRRRRXW#B:                                                              ,,=:                                                                                                                                                                                             
VVVVVXXXXXXRRXXXRRXRRRRRRRRRBRRRRRRRRBXB##i                                                                   .;;                                                                                                                                                                                           
VVVXVXXXXXXXRXXRRRXRRRRRRRRRRRRRRRRRRMM#B.                                                                      .,                                                                                                                                                                                          
YVVVXXXXXXXXXXXRRRRRXXRRRRRRRRRRRRRRR##+                                                                          ,.                                                                                                                                                                                        
YVXXXXXXXXXRRRRRRXXXXXRRRRRRXBRRBBRB##                                                                              ,:.                                                                                                                                                                                     
YVXXXXXXXRRRRRRRRRXRRRRRRRRRBXBRXR##Y                                                                                ,.                                                                                                                                                                                     
VVXXXXXXXRRRRXXXRRRRRRRRRXRRRXRXM##t                                                                                                                                                                                                                                                                        
VXXXXXRRRRRBBRRRRRRRRRRRRRRRRRXM#Y                                                                                                                                                                                                                                                                          
XXXRXXRRRRRRRRRRRRRRRRRRRRRRBX##t                                                                                                                                                                                                                                                                           
XXXXXXRRRRRRRRRRRRRRRRRRRRRRR#B.                                                                                                                                                                                                                                                                            
XXXXRXRRRRRRRRRRRRRRRRRRRRRR##;                                                                                                                                                                                                                                                                             
XXRXRRRRRRRRRRRRRRRRRRRRRRB#M;                                                                                                                                                                                                                                                                              
XXXXXRRRRRRRRRRRRRRRRRRRRRMB.                                                                                                                                                                                                                                                                               
XXXXXRRRRRRRRRRRRRRRBRRRRBWY                                                                                                                                                                                                                                                                                
XRRRRRRRRRRRRRRRRRRXRBRXB##i                                                                                                                                                                                                                                                                                
XXXXXRRRRRRRRRRRRRRBXRRBRi
`}
        </pre>
      </div>
    </section>
  );
};

export default AsciiArtPortrait;